[package]
name = "flexible-calendar"
version = "0.1.0"
authors = ["slhmy <1484836413@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
